### ISSUE TITLE
running project

### ISSUE THREAD

**Issue by UrosRiznic** [filchy/slam#4]
How do you run this thing ? 
Just by " python slam.py video.mp4 " command ? 
And if so, what should be result ? 

Could you please add some more informations in readme file, so we can understand it better ?

**Comment by willxxy** [comment]
@UrosRiznic 

Hi Uros,

I do not know if you are still interested in this but to run it you cd into the forked repo. and type `python3 main.py` . Make sure you to take a look at the other python files because you may need to change the dimensionality of the videos
