### ISSUE TITLE
3D Reconstruction of entire scene.

### ISSUE THREAD

**Issue by sajiidx** [filchy/slam#5]
How can we perform 3d reconstruction using 3d point clouds that are being generated of each frame and combine/merge into one Map/Scene. I am currently understanding you work and wants to push it further by performing 3D reconstruction of Indoor Environments. Could you please guide sir!

**Comment by filchy** [comment]
Hello, simply you can use and merge two libraries (pangolin, OpenGL). Hope it´s enough. If you have any questions I will gladly answer.
